---
here---
title: "biol708 practice data vizs"
format: html
editor: visual
---

## Practicing Data Visualization

```{r}
install.packages("here")

#Load National Parks data

#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")

#make some plots
ggplot(ca) +geom_point(aes(x=year, y=visitors, color=park_name))+ labs(y='Visitation', title='National Park Visitors')+ theme_dark() + theme(legend.title=element_blank())

#visitors by state for visit_16
#ggplot(visit_16) +geom_point(aes(x=state , y=visitors))

#SE parks
ggplot(se) +geom_point(aes(x=year, y=visitors, color=state))+ labs(y='Visitation', title='Southeast U.S. National Park Visitors') + theme(legend.title=element_blank()) + theme(axis.text.x=element_text(angle=45, size=8))

# boxplot for SE parks
ggplot(se) + geom_boxplot(aes(x=park_name, y=visitors)) 

ggplot(se) + geom_point(aes(x=year, y=visitors))+ facet_wrap(~state, scale='free') + xlim(c(1930,2020))

ggplot(se)+ geom_line(aes(x=year, y=visitors, color=park_name)) + geom_point(aes(x=year, y=visitors, color=park_name))+ geom_smooth(aes(x=year, y=visitors, color=park_name))
```

## Data Wrangling

```{r}
library(tidyverse)

gapminder<- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

head(gapminder)
tail(gapminder)
str(gapminder)

unique(gapminder$continent)
summary(gapminder$lifeExp)

filter(gapminder, lifeExp<29)

filter(gapminder, country=='Mexico')

filter(gapminder, country %in% c('Mexico','Peru'))

#creates new data set with given parameters
PeruMex<-filter(gapminder, country %in% c('Mexico', 'Peru'))

Brazil<-filter(gapminder, country=='Brazil',year>1986)
mean(Brazil$lifeExp)


select(gapminder,-year)

#use select and filter together
gap_cambodia<-filter(gapminder, country=='Cambodia')
gap_cambodia2<-select(gap_cambodia, -lifeExp, -continent)

#pipe function
gapminder %>% head()
gap_cambodia<-gapminder %>%
  filter(country=='Cambodia') %>%
  select(-continent, -lifeExp)

gapminder %>%
  mutate(gdp=pop*gdpPercap)

Asia2007<-gapminder %>%
  filter(continent=='Asia', year==2007) %>%
  mutate(popThousands = pop/1000)

#group_by()
gapminder %>%
  filter(year==2002) %>%
  group_by(continent) %>% 
  mutate(cont_pop = sum(pop)) %>%
  ungroup()

cont_pop<-gapminder %>%
  group_by(continent, year) %>%
  summarise(cont_pop = sum(pop)) %>%
  arrange(year)

gapminder %>%
  mutate(gdp = pop * gdpPercap) %>%
  group_by(continent) %>%
  mutate(max_gdp = max(gdp)) %>%
  filter(gdp == max_gdp)

AsiaLE<-gapminder %>%
  filter(continent=='Asia') %>%
  summarize(MaxLE = max(lifeExp)) %>%
  arrange(year)

```
